### ISSUE TITLE
No Linter or Ide Found in qodana.yml

### ISSUE THREAD

**Issue by clFaster** [JetBrains/qodana-cli#403]
I always receive the following error when I try to run the Qodana CLI with my project
 
```
 No valid `linter:` or `ide:` field found in qodana.yml. Have you run qodana init? Running that for you...
/  Scanning project... (0s)
```

The qodana.yml file looks like this. I specified the linter, but have now Idea what the ide prop should be?
```
version: "1.0"
linter: jetbrains/qodana-dotnet:latest
profile:
  name: qodana.recommended.full
dotnet:
  project: MyProject.csproj
```

I do run qodana like this
`qodana scan -e "xxx" --config qodana.yml`
